import TopNav from "./components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import styles from "../styles/page.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Website title</title>
      </head>
      <body className={inter.className}>
        <TopNav />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
